2023-09-04 10:04:57
found 0 new items
2023-09-04 10:06:17
found 0 new items
2023-09-04 10:08:17
found 0 new items
2023-09-04 10:10:37
found 0 new items
2023-09-04 10:13:17
found 0 new items
2023-09-04 10:16:17
found 0 new items
2023-09-04 10:18:37
found 0 new items
2023-09-04 10:19:17
found 0 new items
2023-09-04 10:21:17
found 0 new items
2023-09-04 10:22:37
found 0 new items
2023-09-04 10:23:17
found 0 new items
2023-09-04 10:24:57
found 0 new items
2023-09-04 10:26:17
found 0 new items
2023-09-04 10:27:17
found 0 new items
2023-09-04 10:28:17
found 0 new items
2023-09-04 10:29:37
found 0 new items
2023-09-04 10:31:17
found 0 new items
2023-09-04 10:32:17
found 0 new items
2023-09-04 10:35:17
found 0 new items
2023-09-04 10:36:17
found 0 new items
2023-09-04 10:38:17
found 0 new items
2023-09-04 10:41:17
found 0 new items
2023-09-04 10:42:17
found 0 new items
2023-09-04 10:43:17
found 0 new items
2023-09-04 10:44:57
found 0 new items
2023-09-04 10:46:37
found 0 new items
2023-09-04 10:47:17
found 0 new items
2023-09-04 10:49:37
found 0 new items
2023-09-04 10:50:37
found 0 new items
2023-09-04 10:51:16
found 0 new items
2023-09-04 10:52:17
found 0 new items
2023-09-04 10:54:57
found 0 new items
2023-09-04 10:59:57
found 0 new items
2023-09-04 11:00:17
found 0 new items
2023-09-04 11:02:17
found 0 new items
2023-09-04 11:04:37
found 0 new items
2023-09-04 11:08:37
found 0 new items
2023-09-04 11:11:16
found 0 new items
2023-09-04 11:12:57
found 0 new items
2023-09-04 11:13:17
found 0 new items
2023-09-04 11:57:03
Traceback (most recent call last):
  File "/home/laluna/summer2023/rosa_emic.py", line 160, in <module>
    checker.check_and_update()
  File "/home/laluna/summer2023/rosa_emic.py", line 61, in check_and_update
    response = self.table.scan(
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the Scan operation: Signature not yet current: 20230904T035704Z is still later than 20230904T035408Z (20230904T033908Z + 15 min.)
2023-09-04 11:57:22
Traceback (most recent call last):
  File "/home/laluna/summer2023/rosa_emic.py", line 160, in <module>
    checker.check_and_update()
  File "/home/laluna/summer2023/rosa_emic.py", line 61, in check_and_update
    response = self.table.scan(
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the Scan operation: Signature not yet current: 20230904T035722Z is still later than 20230904T035427Z (20230904T033927Z + 15 min.)
2023-09-04 11:57:42
Traceback (most recent call last):
  File "/home/laluna/summer2023/rosa_emic.py", line 160, in <module>
    checker.check_and_update()
  File "/home/laluna/summer2023/rosa_emic.py", line 61, in check_and_update
    response = self.table.scan(
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the Scan operation: Signature not yet current: 20230904T035742Z is still later than 20230904T035447Z (20230904T033947Z + 15 min.)
2023-09-04 11:58:02
Traceback (most recent call last):
  File "/home/laluna/summer2023/rosa_emic.py", line 160, in <module>
    checker.check_and_update()
  File "/home/laluna/summer2023/rosa_emic.py", line 61, in check_and_update
    response = self.table.scan(
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the Scan operation: Signature not yet current: 20230904T035802Z is still later than 20230904T035507Z (20230904T034007Z + 15 min.)
2023-09-04 11:58:22
Traceback (most recent call last):
  File "/home/laluna/summer2023/rosa_emic.py", line 160, in <module>
    checker.check_and_update()
  File "/home/laluna/summer2023/rosa_emic.py", line 61, in check_and_update
    response = self.table.scan(
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the Scan operation: Signature not yet current: 20230904T035822Z is still later than 20230904T035527Z (20230904T034027Z + 15 min.)
2023-09-04 11:58:42
Traceback (most recent call last):
  File "/home/laluna/summer2023/rosa_emic.py", line 160, in <module>
    checker.check_and_update()
  File "/home/laluna/summer2023/rosa_emic.py", line 61, in check_and_update
    response = self.table.scan(
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the Scan operation: Signature not yet current: 20230904T035842Z is still later than 20230904T035547Z (20230904T034047Z + 15 min.)
2023-09-04 11:59:02
Traceback (most recent call last):
  File "/home/laluna/summer2023/rosa_emic.py", line 160, in <module>
    checker.check_and_update()
  File "/home/laluna/summer2023/rosa_emic.py", line 61, in check_and_update
    response = self.table.scan(
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the Scan operation: Signature not yet current: 20230904T035903Z is still later than 20230904T035607Z (20230904T034107Z + 15 min.)
2023-09-04 11:59:22
Traceback (most recent call last):
  File "/home/laluna/summer2023/rosa_emic.py", line 160, in <module>
    checker.check_and_update()
  File "/home/laluna/summer2023/rosa_emic.py", line 61, in check_and_update
    response = self.table.scan(
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the Scan operation: Signature not yet current: 20230904T035923Z is still later than 20230904T035627Z (20230904T034127Z + 15 min.)
2023-09-04 11:59:42
Traceback (most recent call last):
  File "/home/laluna/summer2023/rosa_emic.py", line 160, in <module>
    checker.check_and_update()
  File "/home/laluna/summer2023/rosa_emic.py", line 61, in check_and_update
    response = self.table.scan(
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/laluna/Desktop/py395e/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the Scan operation: Signature not yet current: 20230904T035943Z is still later than 20230904T035647Z (20230904T034147Z + 15 min.)
